# Masscan Config for ScanCannon (this is just a renamed masscan.conf file)
# See https://github.com/robertdavidgraham/masscan for options and warnings

rate = 5000.00
excludefile = exclude.txt
# Only scan ports that ScanCannon actually categorizes and extracts
ports = 445
output-status = all
output-append = true

# Auto-detected network adapter settings

# Auto-detected network adapter settings

# Auto-detected network adapter settings

# Auto-detected network adapter settings

# Auto-detected network adapter settings

# Auto-detected network adapter settings

# Auto-detected network adapter settings

# Auto-detected network adapter settings
adapter-ip = 192.168.0.202
adapter-mac = 8c-3b-ad-c0-8a-79
router-mac = 08-bf-b8-51-a6-98
